# Generated by Django 3.2.5 on 2021-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Тэг')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('author', models.CharField(blank=True, max_length=120, null=True, verbose_name='Автор')),
                ('publish_date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='blog/%Y/%m/%d', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Описание')),
                ('tags', models.ManyToManyField(related_name='tags', to='blog.TagsModel')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
