# Generated by Django 3.2.5 on 2021-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Показывать?'),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
