# Generated by Django 3.2.5 on 2021-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210803_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
