# Generated by Django 3.2.5 on 2021-08-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-date_publish'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
