# Generated by Django 3.2.5 on 2021-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('room_size', models.IntegerField(blank=True, null=True, verbose_name='Размер комнаты')),
                ('bed', models.IntegerField(blank=True, null=True, verbose_name='Колличество кроватей')),
                ('max_people', models.IntegerField(blank=True, null=True, verbose_name='Максимальное колличество людей')),
                ('wifi', models.CharField(choices=[('a', 'Available'), ('n', 'No available')], max_length=120, verbose_name='Wifi')),
                ('room_service', models.CharField(choices=[('a', 'Available'), ('n', 'No available')], max_length=120, verbose_name='Уборка комнат')),
                ('breakfast', models.CharField(choices=[('i', 'Included'), ('n', 'Not included')], max_length=120, verbose_name='Завтрак')),
                ('layndry', models.CharField(choices=[('a', 'Available'), ('n', 'No available')], max_length=120, verbose_name='Прачечная')),
                ('taxi', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=120, verbose_name='Такси до аэропорта')),
                ('available', models.BooleanField(default=True, verbose_name='Свободен или нет')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
