# Generated by Django 3.2.5 on 2021-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Свободен?'),
        ),
    ]
