# Generated by Django 3.2.5 on 2021-08-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210731_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModelReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_naem', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('additional_node', models.TextField(verbose_name='Дополнительное примечание')),
                ('check_in', models.DateField(verbose_name='Дата заселения')),
                ('check_out', models.DateField(verbose_name='Дата выселения')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='reservation.roommodel')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Зарезервированные комнаты',
            },
        ),
    ]
