# Generated by Django 3.2.5 on 2021-08-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_roommodelreserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodelreserved',
            name='check_in',
            field=models.DateField(null=True, verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='roommodelreserved',
            name='check_out',
            field=models.DateField(null=True, verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='roommodelreserved',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='reservation.roommodel'),
        ),
    ]
