# Generated by Django 3.2.5 on 2021-08-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210801_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommodelreserved',
            old_name='last_naem',
            new_name='last_name',
        ),
    ]
