# Generated by Django 3.2.5 on 2021-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_rename_last_naem_roommodelreserved_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='room_type',
            field=models.CharField(choices=[('b', 'Basic'), ('p', 'Premium')], default='b', max_length=120, verbose_name='Тип комнаты'),
        ),
    ]
